all: cliente/cliente.c, cliente/packets.h
	mklabtel /tmp/cliente cliente/cliente.c, cliente/packets.h
clean:
	rm -f *.~
#ojo con las tabulaciones, se necesitan pero el kdevelop las sustituye, generalmente, por espacios